#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
echo "$(git rev-parse --abbrev-ref HEAD)"

if [ "$(git rev-parse --abbrev-ref HEAD)" = main ]; then echo 'Cannot push directly to main branch'; exit 1; fi
if [ "$(git rev-parse --abbrev-ref HEAD)" = dev ]; then echo 'Cannot push directly to dev branch'; exit 1; fi
